spring:
  application:
    name: cards-service
  datasource:
    #url: ${DB_URL:jdbc:mysql://localhost:2323/${DB_SCHEMA:eazybank}}
    #username: ${DB_USER_NAME:root}
    #password: ${DB_PASSWORD:Root@3064016837}
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USER_NAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9000



build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932

